import type { FixType } from "./enums.js";

/**
 * A concrete fix action to be applied to an export.
 * Generated by the fix planner from SuggestedFix instances.
 */
export interface FixAction {
  fixId: string;
  fixType: FixType;
  /** The rule that triggered this fix */
  ruleId: string;
  /** Element in the document to fix */
  elementRef: string;
  description: string;
  /** Parameters for the fix implementation */
  params: Record<string, unknown>;
}

/** Outcome of applying a fix action */
export interface FixResult {
  fixId: string;
  fixType: FixType;
  success: boolean;
  detail: string;
  /** Before value (for audit trail) */
  beforeValue?: string;
  /** After value (for audit trail) */
  afterValue?: string;
}
